/* global React, Motion */
const { useState, useEffect, useRef } = React;
const { motion, AnimatePresence } = window.Motion;

function MIcon({ name, className = "", style }) {
  return <span className={"material-symbols-rounded " + className} style={style}>{name}</span>;
  }

  function ArrowUpRight({ size = 18, className = "" }) {
    return (
        <svg width={size} height={size} viewBox="0 0 24 24" fill="none" className={className}
                 stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
                       <path d="M7 17 17 7" /><path d="M8 7h9v9" />
                           </svg>
                             );
                             }

                             function PlayIcon({ size = 16, className = "" }) {
                               return (
                                   <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" className={className}>
                                         <path d="M8 5v14l11-7z" />
                                             </svg>
                                               );
                                               }

                                               function useInView(amount = 0.2, once = true) {
                                                 const ref = useRef(null);
                                                   const [inView, setInView] = useState(false);
                                                     useEffect(() => {
                                                         const el = ref.current; if (!el) return;
                                                             const io = new IntersectionObserver((entries) => {
                                                                   entries.forEach(e => {
                                                                           if (e.isIntersecting) { setInView(true); if (once) io.unobserve(el); }
                                                                                   else if (!once) setInView(false);
                                                                                         });
                                                                                             }, { threshold: amount });
                                                                                                 io.observe(el);
                                                                                                     return () => io.disconnect();
                                                                                                       }, [amount, once]);
                                                                                                         return [ref, inView];
                                                                                                         }

                                                                                                         function Reveal({ children, delay = 0, y = 20, className = "", as = "div", style }) {
                                                                                                           const [ref, inView] = useInView(0.15);
                                                                                                             const MComp = motion[as] || motion.div;
                                                                                                               return (
                                                                                                                   <MComp ref={ref} className={className} style={style}
                                                                                                                         initial={{ filter: "blur(10px)", opacity: 0, y }}
                                                                                                                               animate={inView ? { filter: "blur(0px)", opacity: 1, y: 0 } : {}}
                                                                                                                                     transition={{ duration: 0.8, ease: "easeOut", delay }}>
                                                                                                                                           {children}
                                                                                                                                               </MComp>
                                                                                                                                                 );
                                                                                                                                                 }

                                                                                                                                                 function BlurText({ text, className = "", delay = 0, stagger = 0.08 }) {
                                                                                                                                                   const [ref, inView] = useInView(0.2);
                                                                                                                                                     const words = String(text).split(" ");
                                                                                                                                                       return (
                                                                                                                                                           <span ref={ref} className={className} style={{ display: "inline" }}>
                                                                                                                                                                 {words.map((w, i) => (
                                                                                                                                                                         <motion.span key={i}
                                                                                                                                                                                   style={{ display: "inline-block", marginRight: i < words.length - 1 ? "0.26em" : 0 }}
                                                                                                                                                                                             initial={{ filter: "blur(12px)", opacity: 0, y: "0.3em" }}
                                                                                                                                                                                                       animate={inView ? { filter: "blur(0px)", opacity: 1, y: 0 } : {}}
                                                                                                                                                                                                                 transition={{ duration: 0.6, ease: "easeOut", delay: delay + i * stagger }}>
                                                                                                                                                                                                                           {w}
                                                                                                                                                                                                                                   </motion.span>
                                                                                                                                                                                                                                         ))}
                                                                                                                                                                                                                                             </span>
                                                                                                                                                                                                                                               );
                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                               const FADE_MS = 500;
                                                                                                                                                                                                                                               const FADE_OUT_LEAD = 0.55;

                                                                                                                                                                                                                                               function FadingVideo({ src, className = "", style }) {
                                                                                                                                                                                                                                                 const aRef = useRef(null), bRef = useRef(null);
                                                                                                                                                                                                                                                   const activeRef = useRef("a"), fadingRef = useRef(false), rafRef = useRef(0);
                                                                                                                                                                                                                                                     const [failed, setFailed] = useState(false);
                                                                                                                                                                                                                                                       useEffect(() => {
                                                                                                                                                                                                                                                           const a = aRef.current, b = bRef.current;
                                                                                                                                                                                                                                                               if (!a || !b) return;
                                                                                                                                                                                                                                                                   a.style.opacity = "1"; b.style.opacity = "0";
                                                                                                                                                                                                                                                                       const startFade = () => {
                                                                                                                                                                                                                                                                             if (fadingRef.current) return;
                                                                                                                                                                                                                                                                                   fadingRef.current = true;
                                                                                                                                                                                                                                                                                         const from = activeRef.current === "a" ? a : b;
                                                                                                                                                                                                                                                                                               const to = activeRef.current === "a" ? b : a;
                                                                                                                                                                                                                                                                                                     try { to.currentTime = 0; const p = to.play(); if (p) p.catch(() => {}); } catch(e) {}
                                                                                                                                                                                                                                                                                                           const t0 = performance.now();
                                                                                                                                                                                                                                                                                                                 const tick = (now) => {
                                                                                                                                                                                                                                                                                                                         const k = Math.min(1, (now - t0) / FADE_MS);
                                                                                                                                                                                                                                                                                                                                 to.style.opacity = String(k); from.style.opacity = String(1 - k);
                                                                                                                                                                                                                                                                                                                                         if (k < 1) { rafRef.current = requestAnimationFrame(tick); }
                                                                                                                                                                                                                                                                                                                                                 else { try { from.pause(); } catch(e) {} activeRef.current = activeRef.current === "a" ? "b" : "a"; fadingRef.current = false; }
                                                                                                                                                                                                                                                                                                                                                       };
                                                                                                                                                                                                                                                                                                                                                             rafRef.current = requestAnimationFrame(tick);
                                                                                                                                                                                                                                                                                                                                                                 };
                                                                                                                                                                                                                                                                                                                                                                     const onTime = (e) => {
                                                                                                                                                                                                                                                                                                                                                                           const v = e.target;
                                                                                                                                                                                                                                                                                                                                                                                 const isActive = (activeRef.current === "a" && v === a) || (activeRef.current === "b" && v === b);
                                                                                                                                                                                                                                                                                                                                                                                       if (!isActive || fadingRef.current) return;
                                                                                                                                                                                                                                                                                                                                                                                             if (v.duration && v.currentTime >= v.duration - FADE_OUT_LEAD) startFade();
                                                                                                                                                                                                                                                                                                                                                                                                 };
                                                                                                                                                                                                                                                                                                                                                                                                     const onEnded = (e) => { const v = e.target; try { v.currentTime = 0; const p = v.play(); if (p) p.catch(() => {}); } catch(er) {} };
                                                                                                                                                                                                                                                                                                                                                                                                         const onErr = () => setFailed(true);
                                                                                                                                                                                                                                                                                                                                                                                                             a.addEventListener("timeupdate", onTime); b.addEventListener("timeupdate", onTime);
                                                                                                                                                                                                                                                                                                                                                                                                                 a.addEventListener("ended", onEnded); b.addEventListener("ended", onEnded);
                                                                                                                                                                                                                                                                                                                                                                                                                     a.addEventListener("error", onErr);
                                                                                                                                                                                                                                                                                                                                                                                                                         const p = a.play(); if (p) p.catch(() => {});
                                                                                                                                                                                                                                                                                                                                                                                                                             return () => { cancelAnimationFrame(rafRef.current); a.removeEventListener("timeupdate", onTime); b.removeEventListener("timeupdate", onTime); a.removeEventListener("ended", onEnded); b.removeEventListener("ended", onEnded); a.removeEventListener("error", onErr); };
                                                                                                                                                                                                                                                                                                                                                                                                                               }, [src]);
                                                                                                                                                                                                                                                                                                                                                                                                                                 if (failed) return <div className={"hero-fallback " + className} style={style} />;
                                                                                                                                                                                                                                                                                                                                                                                                                                   const vStyle = { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", willChange: "opacity" };
                                                                                                                                                                                                                                                                                                                                                                                                                                     return (
                                                                                                                                                                                                                                                                                                                                                                                                                                         <div className={className} style={{ position: "absolute", inset: 0, overflow: "hidden", ...style }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                               <video ref={aRef} style={vStyle} src={src} muted playsInline preload="auto" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                     <video ref={bRef} style={{ ...vStyle, opacity: 0 }} src={src} muted playsInline preload="auto" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                           );
                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                           function Counter({ to, suffix = "", duration = 1600, className = "" }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                             const ref = useRef(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                               const [val, setVal] = useState(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const done = useRef(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const el = ref.current; if (!el) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const io = new IntersectionObserver((entries) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 entries.forEach(en => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (en.isIntersecting && !done.current) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   done.current = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const t0 = performance.now();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const step = (now) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const k = Math.min(1, (now - t0) / duration);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               setVal(Math.round(to * (1 - Math.pow(1 - k, 3))));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (k < 1) requestAnimationFrame(step);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               requestAnimationFrame(step);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }, { threshold: 0.5 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     io.observe(el);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return () => io.disconnect();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }, [to, duration]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return <span ref={ref} className={className}>{val}{suffix}</span>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             function useParallax(strength = 0.08) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const ref = useRef(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const el = ref.current; if (!el) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         let raf = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const update = () => { const rect = el.getBoundingClientRect(); const center = rect.top + rect.height / 2 - window.innerHeight / 2; el.style.transform = `translateY(${(-center * strength).toFixed(1)}px)`; raf = 0; };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const onScroll = () => { if (!raf) raf = requestAnimationFrame(update); };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     window.addEventListener("scroll", onScroll, { passive: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         update();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return () => { window.removeEventListener("scroll", onScroll); cancelAnimationFrame(raf); };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }, [strength]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return ref;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 function useCustomCursor() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (window.matchMedia("(pointer: coarse)").matches) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const dot = document.getElementById("cursorDot");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const ring = document.getElementById("cursorRing");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (!dot || !ring) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       let mx = window.innerWidth / 2, my = window.innerHeight / 2, rx = mx, ry = my, raf = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const onMove = (e) => { mx = e.clientX; my = e.clientY; dot.style.transform = `translate(${mx}px,${my}px)`; if (e.target.closest("a,button,.cursor-hover")) ring.classList.add("is-hover"); else ring.classList.remove("is-hover"); };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const loop = () => { rx += (mx - rx) * 0.18; ry += (my - ry) * 0.18; ring.style.transform = `translate(${rx}px,${ry}px)`; raf = requestAnimationFrame(loop); };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   window.addEventListener("mousemove", onMove);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       loop();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return () => { window.removeEventListener("mousemove", onMove); cancelAnimationFrame(raf); };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }, []);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             function GradientPlaceholder({ from, to, label, className = "", style }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div className={className} style={{ background: `linear-gradient(135deg,${from},${to})`, position: "relative", overflow: "hidden", ...style }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div style={{ position: "absolute", inset: 0, backgroundImage: "repeating-linear-gradient(45deg,rgba(255,255,255,0.05) 0 2px,transparent 2px 9px)" }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               {label && <span style={{ position: "absolute", bottom: 10, left: 12, fontFamily: "ui-monospace,monospace", fontSize: 10, letterSpacing: "0.06em", textTransform: "uppercase", color: "rgba(255,255,255,0.65)" }}>{label}</span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     function Kicker({ children }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <Reveal as="div" className="font-body text-sm md:text-base tracking-[0.25em] uppercase text-white/55 mb-5" style={{ fontFamily: "ui-monospace,monospace" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {children}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </Reveal>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Object.assign(window, { MIcon, ArrowUpRight, PlayIcon, useInView, Reveal, BlurText, FadingVideo, Counter, useParallax, useCustomCursor, GradientPlaceholder, Kicker });