/* global React, Motion, MIcon, ArrowUpRight, PlayIcon, Reveal, BlurText, FadingVideo, Counter, Kicker */
const { useState: useStateA, useEffect: useEffectA } = React;
const { motion: motionA, AnimatePresence: AnimatePresenceA } = window.Motion;

const NAV_LINKS = [
  { label: "Home", href: "#hero" },
    { label: "Yoga", href: "#yoga" },
      { label: "Fitness", href: "#fitness" },
        { label: "Basquet", href: "#basquet" },
          { label: "Membresias", href: "#membresias" },
            { label: "Contacto", href: "#contacto" },
            ];

            function Navbar() {
              const [open, setOpen] = useStateA(false);
                useEffectA(() => { document.body.classList.toggle("no-scroll", open); return () => document.body.classList.remove("no-scroll"); }, [open]);
                  const go = (href) => (e) => { e.preventDefault(); setOpen(false); const el = document.querySelector(href); if (el) el.scrollIntoView({ behavior: "smooth", block: "start" }); };
                    return (
                        <header className="fixed top-4 left-0 right-0 z-50 px-5 md:px-8 lg:px-16">
                              <div className="flex items-center justify-between gap-4">
                                      <a href="#hero" onClick={go("#hero")} className="liquid-glass w-12 h-12 rounded flex items-center justify-center shrink-0"><span className="font-heading italic text-2xl leading-none">M</span></a>
                                              <nav className="hidden lg:flex items-center gap-1 liquid-glass rounded px-2 py-2">
                                                        {NAV_LINKS.map(l => (<a key={l.label} href={l.href} onClick={go(l.href)} className="px-4 py-2 rounded text-sm text-white/80 hover:text-white hover:bg-white/10 transition-colors">{l.label}</a>))}
                                                                </nav>
                                                                        <div className="flex items-center gap-3">
                                                                                  <a href="#contacto" onClick={go("#contacto")} className="hidden lg:flex items-center gap-1.5 bg-white text-black rounded pl-5 pr-4 py-2.5 text-sm font-medium hover:bg-white/90 transition-colors">Unete Ahora <ArrowUpRight size={16} /></a>
                                                                                            <button onClick={() => setOpen(v => !v)} aria-label="Menu" className="lg:hidden liquid-glass w-12 h-12 rounded flex items-center justify-center"><MIcon name={open ? "close" : "menu"} className="text-2xl" /></button>
                                                                                                      <div className="hidden lg:block w-12 h-12 shrink-0" aria-hidden="true" />
                                                                                                              </div>
                                                                                                                    </div>
                                                                                                                          <AnimatePresenceA>{open && (<motionA.nav initial={{ opacity: 0, y: -12, filter: "blur(8px)" }} animate={{ opacity: 1, y: 0, filter: "blur(0px)" }} exit={{ opacity: 0, y: -12, filter: "blur(8px)" }} transition={{ duration: 0.35, ease: "easeOut" }} className="lg:hidden liquid-glass-strong rounded-[1.5rem] mt-3 p-3 flex flex-col">{NAV_LINKS.map(l => (<a key={l.label} href={l.href} onClick={go(l.href)} className="px-4 py-3 rounded text-lg text-white/85 hover:bg-white/10 transition-colors">{l.label}</a>))}<a href="#contacto" onClick={go("#contacto")} className="mt-2 flex items-center justify-center gap-1.5 bg-white text-black rounded py-3 font-medium">Unete Ahora <ArrowUpRight size={16} /></a></motionA.nav>)}</AnimatePresenceA>
                                                                                                                              </header>
                                                                                                                                );
                                                                                                                                }

                                                                                                                                const blurIn = (delay) => ({ initial: { filter: "blur(10px)", opacity: 0, y: 20 }, animate: { filter: "blur(0px)", opacity: 1, y: 0 }, transition: { duration: 0.9, ease: "easeOut", delay } });

                                                                                                                                function Hero() {
                                                                                                                                  const [vidFail, setVidFail] = useStateA(false);
                                                                                                                                    return (
                                                                                                                                        <section id="hero" className="relative min-h-screen w-full overflow-hidden bg-black">
                                                                                                                                              {!vidFail ? (<video className="absolute left-1/2 top-0 -translate-x-1/2 object-cover object-top z-0" style={{ width: "120%", height: "120%" }} src="https://videos.pexels.com/video-files/6261067/6261067-uhd_2560_1440_25fps.mp4" autoPlay muted loop playsInline preload="auto" onError={() => setVidFail(true)} />) : (<div className="hero-fallback absolute inset-0 z-0" />)}
                                                                                                                                                    <div className="relative z-10 min-h-screen flex flex-col items-center justify-center text-center pt-24 pb-16 px-4">
                                                                                                                                                            <motionA.div {...blurIn(0.4)} className="liquid-glass rounded inline-flex items-center gap-2.5 pl-1.5 pr-4 py-1.5 mb-8"><span className="bg-white text-black rounded text-xs font-medium px-3 py-1">Nuevo</span><span className="text-sm text-white/85">Estudio premium de Yoga, Fitness y Basquet</span></motionA.div>
                                                                                                                                                                    <h1 className="font-heading italic text-white text-6xl md:text-7xl lg:text-[5.5rem] leading-[0.85] tracking-[-0.04em] max-w-5xl"><BlurText text="Mueve Tu Cuerpo. Eleva Tu Mente." delay={0.6} stagger={0.07} /></h1>
                                                                                                                                                                            <motionA.p {...blurIn(0.8)} className="mt-7 max-w-2xl text-lg md:text-xl text-white/75 font-light leading-relaxed" style={{ textWrap: "balance" }}>Tres disciplinas. Un solo lugar. Clases de yoga, entrenamientos de alto rendimiento y basquet profesional para todos los niveles.</motionA.p>
                                                                                                                                                                                    <motionA.div {...blurIn(1.1)} className="mt-9 flex flex-wrap items-center justify-center gap-4">
                                                                                                                                                                                              <a href="#yoga" onClick={e => { e.preventDefault(); document.querySelector("#yoga").scrollIntoView({ behavior:"smooth" }); }} className="liquid-glass-strong rounded inline-flex items-center gap-2 pl-6 pr-5 py-3.5 text-base font-medium hover:bg-white/20 transition-colors">Explorar Clases <ArrowUpRight size={18} /></a>
                                                                                                                                                                                                        <a href="#galeria" onClick={e => { e.preventDefault(); document.querySelector("#galeria").scrollIntoView({ behavior:"smooth" }); }} className="inline-flex items-center gap-2 text-base text-white/85 hover:text-white px-2 py-2 transition-colors"><span className="liquid-glass w-9 h-9 rounded flex items-center justify-center"><PlayIcon size={14} /></span>Ver el Estudio</a>
                                                                                                                                                                                                                </motionA.div>
                                                                                                                                                                                                                        <motionA.div {...blurIn(1.3)} className="mt-12 flex flex-wrap items-stretch justify-center gap-4">
                                                                                                                                                                                                                                  <div className="liquid-glass w-[220px] rounded-[1.25rem] p-5 text-left flex flex-col gap-2"><MIcon name="schedule" className="text-2xl text-white/70" /><div className="font-heading italic text-4xl leading-none">500+</div><div className="text-sm text-white/65">Miembros activos</div></div>
                                                                                                                                                                                                                                            <div className="liquid-glass w-[220px] rounded-[1.25rem] p-5 text-left flex flex-col gap-2"><MIcon name="public" className="text-2xl text-white/70" /><div className="font-heading italic text-4xl leading-none">3</div><div className="text-sm text-white/65">Disciplinas en un solo lugar</div></div>
                                                                                                                                                                                                                                                    </motionA.div>
                                                                                                                                                                                                                                                            <motionA.div {...blurIn(1.4)} className="mt-14 flex flex-wrap items-center justify-center gap-x-7 gap-y-3">
                                                                                                                                                                                                                                                                      <span className="liquid-glass rounded px-4 py-2 text-xs uppercase tracking-[0.15em] text-white/70">Nuestras disciplinas</span>
                                                                                                                                                                                                                                                                                {["Yoga","Fitness","Basquet","Mindfulness","Performance"].map(n => (<span key={n} className="font-heading italic text-2xl md:text-3xl text-white/60">{n}</span>))}
                                                                                                                                                                                                                                                                                        </motionA.div>
                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                    function DisciplineCard({ icon, tags, title, body, delay = 0 }) {
                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                          <Reveal delay={delay} className="liquid-glass rounded-[1.5rem] p-7 md:p-8 min-h-[360px] flex flex-col cursor-hover hover:bg-white/10 transition-colors duration-500">
                                                                                                                                                                                                                                                                                                                <div className="liquid-glass-strong w-14 h-14 rounded flex items-center justify-center mb-6"><MIcon name={icon} className="text-3xl" /></div>
                                                                                                                                                                                                                                                                                                                      <div className="flex flex-wrap gap-2 mb-6">{tags.map(t => <span key={t} className="liquid-glass rounded px-3 py-1 text-xs text-white/75">{t}</span>)}</div>
                                                                                                                                                                                                                                                                                                                            <h3 className="font-heading italic text-3xl md:text-4xl mb-3 leading-none">{title}</h3>
                                                                                                                                                                                                                                                                                                                                  <p className="text-white/70 leading-relaxed mt-auto">{body}</p>
                                                                                                                                                                                                                                                                                                                                      </Reveal>
                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        function VideoSection({ id, src, children }) {
                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                              <section id={id} className="relative min-h-screen w-full overflow-hidden bg-black">
                                                                                                                                                                                                                                                                                                                                                    <FadingVideo src={src} className="z-0" />
                                                                                                                                                                                                                                                                                                                                                          <div className="relative z-10 px-6 md:px-16 lg:px-20 pt-28 pb-16">{children}</div>
                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                function TwoLineHeading({ a, b }) {
                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                      <h2 className="font-heading italic text-white text-5xl md:text-7xl lg:text-[6rem] leading-[0.85] tracking-[-0.03em] mb-12">
                                                                                                                                                                                                                                                                                                                                                                            <BlurText text={a} />{" "}<br /><BlurText text={b} delay={0.15} />
                                                                                                                                                                                                                                                                                                                                                                                </h2>
                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                  function Yoga() {
                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                        <VideoSection id="yoga" src="https://videos.pexels.com/video-files/3044483/3044483-uhd_2560_1440_25fps.mp4">
                                                                                                                                                                                                                                                                                                                                                                                              <Kicker>// Yoga</Kicker>
                                                                                                                                                                                                                                                                                                                                                                                                    <TwoLineHeading a="Equilibrio" b="evolucionado" />
                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                                                                                                                                                                                                                                                                                                                                                                                                                  <DisciplineCard delay={0} icon="self_improvement" tags={["Hatha","Vinyasa","Restaurativa","Prenatal"]} title="Clases Grupales" body="Sesiones guiadas para todos los niveles con instructores certificados en un ambiente sereno y luminoso." />
                                                                                                                                                                                                                                                                                                                                                                                                                          <DisciplineCard delay={0.1} icon="spa" tags={["60min","90min","Online","Privada"]} title="Sesion Privada" body="Atencion personalizada adaptada a tu cuerpo, objetivos y ritmo. Progresa mas rapido con guia uno a uno." />
                                                                                                                                                                                                                                                                                                                                                                                                                                  <DisciplineCard delay={0.2} icon="schedule" tags={["Manana","Tarde","Noche","Fin de semana"]} title="Horarios" body="[HORARIO LUNES-VIERNES] - [HORARIO FIN DE SEMANA] consulta disponibilidad en recepcion." />
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </VideoSection>
                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                              function Fitness() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <VideoSection id="fitness" src="https://videos.pexels.com/video-files/4761854/4761854-uhd_2560_1440_25fps.mp4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Kicker>// Fitness</Kicker>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TwoLineHeading a="Alto" b="rendimiento" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5 mb-10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {[{ to:500, suffix:"+", label:"Miembros" },{ to:20, suffix:"+", label:"Clases/semana" },{ to:5, suffix:"", label:"Anos de experiencia" }].map((c,i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Reveal key={c.label} delay={i*0.1} className="liquid-glass rounded-[1.25rem] p-7 flex flex-col gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="font-heading italic text-5xl md:text-6xl leading-none"><Counter to={c.to} suffix={c.suffix} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-white/65">{c.label}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Reveal>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <DisciplineCard delay={0} icon="fitness_center" tags={["Fuerza","Cardio","HIIT","Funcional"]} title="Entrenamiento" body="Equipamiento de ultima generacion y programas disenados para maximizar resultados en el menor tiempo." />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <DisciplineCard delay={0.1} icon="restaurant_menu" tags={["Proteina","Hidratacion","Plan","Suplementos"]} title="Nutricion" body="[PLANES DE NUTRICION DISPONIBLES] consulta con nuestro especialista para tu plan personalizado." />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <DisciplineCard delay={0.2} icon="trending_up" tags={["Basico","Pro","Elite","Premium"]} title="Membresias" body="Desde $[PRECIO]/mes. Acceso ilimitado a equipos, clases grupales y seguimiento de progreso." />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </VideoSection>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Object.assign(window, { Navbar, Hero, Yoga, Fitness, DisciplineCard, VideoSection, TwoLineHeading, blurIn });