fC } = React;

const TESTIMONIALS = [
  { quote:"[TESTIMONIO 1]", name:"[Nombre]", disc:"Yoga", from:"#1f5c3d", to:"#0b2a1b" },
    { quote:"[TESTIMONIO 2]", name:"[Nombre]", disc:"Fitness", from:"#7a3b0f", to:"#2c1606" },
      { quote:"[TESTIMONIO 3]", name:"[Nombre]", disc:"Basquet", from:"#9c4f14", to:"#3a1d09" },
      ];

      function Stars() {
        return (<div className="flex gap-1.5 mb-4">{[0,1,2,3,4].map(i => <span key={i} className="w-2 h-2 rounded" style={{ background:"#ffd24a" }} />)}</div>);
        }

        function TestimonialCard({ t, floatDelay = 0 }) {
          return (
              <div className="liquid-glass rounded-[1.5rem] p-7 cursor-hover" style={{ animation:`floatY 3s ease-in-out ${floatDelay}s infinite` }}>
                    <div className="flex items-center gap-3 mb-5">
                            <GradientPlaceholder from={t.from} to={t.to} style={{ width:48, height:48, borderRadius:"9999px" }} />
                                    <div><div className="font-medium">{t.name}</div><div className="text-xs text-white/55 uppercase tracking-[0.12em]">{t.disc}</div></div>
                                          </div>
                                                <Stars />
                                                      <p className="font-heading italic text-2xl leading-snug text-white/90">{t.quote}</p>
                                                          </div>
                                                            );
                                                            }

                                                            function Testimonios() {
                                                              const [idx, setIdx] = useStateC(0);
                                                                const n = TESTIMONIALS.length;
                                                                  useEffectC(() => { const t = setInterval(() => setIdx(v => (v+1)%n), 5000); return () => clearInterval(t); }, [n]);
                                                                    return (
                                                                        <section id="testimonios" className="relative bg-black px-6 md:px-16 lg:px-20 py-28 overflow-hidden">
                                                                              <Kicker>// Comunidad</Kicker>
                                                                                    <TwoLineHeading a="Lo que dicen" b="nuestros miembros" />
                                                                                          <div className="hidden md:grid grid-cols-3 gap-6">{TESTIMONIALS.map((t,i) => (<Reveal key={i} delay={i*0.12}><TestimonialCard t={t} floatDelay={i*0.6} /></Reveal>))}</div>
                                                                                                <div className="md:hidden">
                                                                                                        <TestimonialCard t={TESTIMONIALS[idx]} />
                                                                                                                <div className="flex items-center justify-center gap-4 mt-6">
                                                                                                                          <button onClick={() => setIdx(v => (v-1+n)%n)} className="liquid-glass w-11 h-11 rounded flex items-center justify-center"><MIcon name="chevron_left" className="text-2xl" /></button>
                                                                                                                                    <div className="flex gap-2">{TESTIMONIALS.map((_,i) => (<span key={i} className="w-2 h-2 rounded transition-colors" style={{ background: i===idx ? "#fff" : "rgba(255,255,255,0.3)" }} />))}</div>
                                                                                                                                              <button onClick={() => setIdx(v => (v+1)%n)} className="liquid-glass w-11 h-11 rounded flex items-center justify-center"><MIcon name="chevron_right" className="text-2xl" /></button>
                                                                                                                                                      </div>
                                                                                                                                                            </div>
                                                                                                                                                                </section>
                                                                                                                                                                  );
                                                                                                                                                                  }

                                                                                                                                                                  const PLANS = [
                                                                                                                                                                    { name:"Basico", price:"[PRECIO]", feats:["Acceso a equipos","2 clases grupales/semana","Horario estandar"], rec:false },
                                                                                                                                                                      { name:"Pro", price:"[PRECIO]", feats:["Todo en Basico","Clases ilimitadas","1 sesion privada/mes","App de seguimiento"], rec:true },
                                                                                                                                                                        { name:"Elite", price:"[PRECIO]", feats:["Todo en Pro","Nutricion personalizada","Acceso 24h","Entrenador dedicado"], rec:false },
                                                                                                                                                                        ];

                                                                                                                                                                        function PlanCard({ plan, delay }) {
                                                                                                                                                                          const ref = useRefC(null);
                                                                                                                                                                            const onMove = (e) => { const el = ref.current; if (!el) return; const r = el.getBoundingClientRect(); el.style.setProperty("--mx",`${e.clientX-r.left}px`); el.style.setProperty("--my",`${e.clientY-r.top}px`); };
                                                                                                                                                                              const recWrap = plan.rec ? { padding:2, borderRadius:"1.6rem", background:"linear-gradient(110deg,#ff7a18,#ffd24a,#1f8a5b,#ff7a18)", backgroundSize:"200% 100%", animation:"borderGlow 4s linear infinite" } : {};
                                                                                                                                                                                return (
                                                                                                                                                                                    <Reveal delay={delay} className={plan.rec ? "md:-mt-4 md:mb-4" : ""}>
                                                                                                                                                                                          <div style={recWrap}>
                                                                                                                                                                                                  <div ref={ref} onMouseMove={onMove} className="liquid-glass rounded-[1.5rem] p-8 h-full flex flex-col cursor-hover relative overflow-hidden" style={{ "--mx":"50%", "--my":"0%" }}>
                                                                                                                                                                                                            <div className="pointer-events-none absolute inset-0 opacity-0 hover:opacity-100 transition-opacity duration-300" style={{ background:"radial-gradient(380px circle at var(--mx) var(--my),rgba(255,255,255,0.16),transparent 60%)" }} />
                                                                                                                                                                                                                      {plan.rec && <span className="self-start bg-white text-black rounded text-xs font-medium px-3 py-1 mb-4">Recomendado</span>}
                                                                                                                                                                                                                                <h3 className="font-heading italic text-4xl mb-1">{plan.name}</h3>
                                                                                                                                                                                                                                          <div className="mb-6"><span className="font-heading italic text-5xl">${plan.price}</span><span className="text-white/55">/mes</span></div>
                                                                                                                                                                                                                                                    <ul className="flex flex-col gap-3 mb-8">{plan.feats.map(f => (<li key={f} className="flex items-center gap-3 text-white/80"><MIcon name="check_circle" className="text-lg text-white/60" /> {f}</li>))}</ul>
                                                                                                                                                                                                                                                              <a href="#contacto" onClick={e => { e.preventDefault(); document.querySelector("#contacto").scrollIntoView({ behavior:"smooth" }); }} className={(plan.rec ? "bg-white text-black hover:bg-white/90 " : "liquid-glass-strong hover:bg-white/20 ") + "mt-auto rounded py-3.5 text-center font-medium transition-colors flex items-center justify-center gap-2"}>Elegir {plan.name} <ArrowUpRight size={16} /></a>
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                </Reveal>
                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                  function Membresias() {
                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                        <section id="membresias" className="relative bg-black px-6 md:px-16 lg:px-20 py-28">
                                                                                                                                                                                                                                                                                              <Kicker>// Planes</Kicker>
                                                                                                                                                                                                                                                                                                    <TwoLineHeading a="Encuentra tu" b="plan perfecto" />
                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-stretch">{PLANS.map((p,i) => <PlanCard key={p.name} plan={p} delay={i*0.1} />)}</div>
                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                function ParticleField() {
                                                                                                                                                                                                                                                                                                                  const mountRef = useRefC(null);
                                                                                                                                                                                                                                                                                                                    useEffectC(() => {
                                                                                                                                                                                                                                                                                                                        if (typeof THREE === "undefined") return;
                                                                                                                                                                                                                                                                                                                            const mount = mountRef.current; if (!mount) return;
                                                                                                                                                                                                                                                                                                                                const w = () => mount.clientWidth, h = () => mount.clientHeight;
                                                                                                                                                                                                                                                                                                                                    const scene = new THREE.Scene();
                                                                                                                                                                                                                                                                                                                                        const camera = new THREE.PerspectiveCamera(60, w()/h(), 0.1, 1000);
                                                                                                                                                                                                                                                                                                                                            camera.position.z = 60;
                                                                                                                                                                                                                                                                                                                                                const renderer = new THREE.WebGLRenderer({ alpha:true, antialias:true });
                                                                                                                                                                                                                                                                                                                                                    renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));
                                                                                                                                                                                                                                                                                                                                                        renderer.setSize(w(), h());
                                                                                                                                                                                                                                                                                                                                                            mount.appendChild(renderer.domElement);
                                                                                                                                                                                                                                                                                                                                                                const COUNT = 80;
                                                                                                                                                                                                                                                                                                                                                                    const base = [], vel = [];
                                                                                                                                                                                                                                                                                                                                                                        const positions = new Float32Array(COUNT*3);
                                                                                                                                                                                                                                                                                                                                                                            for (let i=0; i<COUNT; i++) {
                                                                                                                                                                                                                                                                                                                                                                                  const x=(Math.random()-0.5)*90, y=(Math.random()-0.5)*60, z=(Math.random()-0.5)*30;
                                                                                                                                                                                                                                                                                                                                                                                        base.push([x,y,z]); vel.push([0,0,0]);
                                                                                                                                                                                                                                                                                                                                                                                              positions[i*3]=x; positions[i*3+1]=y; positions[i*3+2]=z;
                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                      const geo = new THREE.BufferGeometry();
                                                                                                                                                                                                                                                                                                                                                                                                          geo.setAttribute("position", new THREE.BufferAttribute(positions,3));
                                                                                                                                                                                                                                                                                                                                                                                                              const mat = new THREE.PointsMaterial({ color:0xffffff, size:0.9, transparent:true, opacity:0.85 });
                                                                                                                                                                                                                                                                                                                                                                                                                  const points = new THREE.Points(geo, mat);
                                                                                                                                                                                                                                                                                                                                                                                                                      scene.add(points);
                                                                                                                                                                                                                                                                                                                                                                                                                          const mouse = new THREE.Vector3(9999,9999,0);
                                                                                                                                                                                                                                                                                                                                                                                                                              const onMove = (e) => { const r = mount.getBoundingClientRect(); mouse.x = ((e.clientX-r.left)/r.width)*2-1; mouse.y = -((e.clientY-r.top)/r.height)*2+1; mouse.x *= 45; mouse.y *= 30; };
                                                                                                                                                                                                                                                                                                                                                                                                                                  mount.addEventListener("mousemove", onMove);
                                                                                                                                                                                                                                                                                                                                                                                                                                      let raf;
                                                                                                                                                                                                                                                                                                                                                                                                                                          const animate = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                const pos = geo.attributes.position.array;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (let i=0; i<COUNT; i++) { const ix=i*3; let px=pos[ix], py=pos[ix+1]; const dx=px-mouse.x, dy=py-mouse.y, dist2=dx*dx+dy*dy; if (dist2<180) { const f=(180-dist2)/180, d=Math.sqrt(dist2)||1; vel[i][0]+=(dx/d)*f*0.6; vel[i][1]+=(dy/d)*f*0.6; } vel[i][0]+=(base[i][0]-px)*0.02; vel[i][1]+=(base[i][1]-py)*0.02; vel[i][0]*=0.9; vel[i][1]*=0.9; pos[ix]=px+vel[i][0]; pos[ix+1]=py+vel[i][1]; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            geo.attributes.position.needsUpdate=true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  points.rotation.z+=0.0004;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderer.render(scene, camera);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              raf=requestAnimationFrame(animate);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      animate();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const onResize = () => { camera.aspect=w()/h(); camera.updateProjectionMatrix(); renderer.setSize(w(),h()); };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.addEventListener("resize", onResize);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return () => { cancelAnimationFrame(raf); window.removeEventListener("resize", onResize); mount.removeEventListener("mousemove", onMove); geo.dispose(); mat.dispose(); renderer.dispose(); if (renderer.domElement.parentNode) renderer.domElement.parentNode.removeChild(renderer.domElement); };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }, []);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return <div ref={mountRef} className="absolute inset-0 z-0" />;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const INPUT_CLS = "liquid-glass rounded px-5 py-3 text-white placeholder-white/50 w-full focus:outline-none focus:bg-white/10 transition-colors";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function Contacto() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const [sent, setSent] = useStateC(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <section id="contacto" className="relative bg-black overflow-hidden" style={{ minHeight:"100vh" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ParticleField />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="relative z-10 px-6 md:px-16 lg:px-20 pt-28 pb-16 flex flex-col items-center text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Kicker>// Contacto</Kicker>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2 className="font-heading italic text-white text-5xl md:text-7xl lg:text-[6rem] leading-[0.85] tracking-[-0.03em] mb-12"><BlurText text="Empieza hoy" /><br /><BlurText text="tu transformacion" delay={0.15} /></h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Reveal className="w-full max-w-lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <form onSubmit={e => { e.preventDefault(); setSent(true); }} className="liquid-glass-strong rounded-[1.5rem] p-8 flex flex-col gap-4 text-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input className={INPUT_CLS} placeholder="Nombre" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <input className={INPUT_CLS} type="email" placeholder="Email" required />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <input className={INPUT_CLS} type="tel" placeholder="Telefono" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="relative"><select className={INPUT_CLS + " appearance-none pr-12"} defaultValue="" required style={{ colorScheme:"dark" }}><option value="" disabled>Disciplina de interes</option><option>Yoga</option><option>Fitness</option><option>Basquet</option><option>Todo</option></select><MIcon name="expand_more" className="absolute right-5 top-1/2 -translate-y-1/2 pointer-events-none text-white/60" /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <textarea className={INPUT_CLS + " rounded-[1.25rem] resize-none"} rows="4" placeholder="Mensaje" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button type="submit" className="liquid-glass-strong rounded py-3.5 font-medium flex items-center justify-center gap-2 hover:bg-white/20 transition-colors">{sent ? "Mensaje enviado!" : <><span>Enviar mensaje</span> <ArrowUpRight size={16} /></>}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Reveal>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <footer className="relative z-10 px-6 md:px-16 lg:px-20 pt-16 pb-10 border-t border-white/10 mt-16">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex items-center gap-4"><span className="liquid-glass w-12 h-12 rounded flex items-center justify-center font-heading italic text-2xl">M</span><span className="font-heading italic text-2xl">Movement Studio</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <nav className="flex flex-wrap gap-x-6 gap-y-2">{["Home","Yoga","Fitness","Basquet","Membresias","Contacto"].map((l,i) => (<a key={l} href={"#"+["hero","yoga","fitness","basquet","membresias","contacto"][i]} className="text-white/60 hover:text-white transition-colors text-sm">{l}</a>))}</nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3 mt-10 text-sm text-white/45">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>2026 Movement Studio. Todos los derechos reservados.</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex flex-wrap gap-x-6 gap-y-1"><span>[DIRECCION]</span><span>[TELEFONO]</span><span>[EMAIL]</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Object.assign(window, { Testimonios, Membresias, Contacto });