ax, VideoSection, DisciplineCard, TwoLineHeading */
const { useRef: useRefB } = React;

function Basquet() {
  return (
      <VideoSection id="basquet" src="https://videos.pexels.com/video-files/5473791/5473791-uhd_2560_1440_25fps.mp4">
            <Kicker>// Basquet</Kicker>
                  <TwoLineHeading a="Juega" b="en grande" />
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                                <DisciplineCard delay={0} icon="sports_basketball" tags={["3x3","5x5","Femenil","Infantil"]} title="Ligas" body="[NOMBRE LIGA] temporada [FECHAS]. Inscripciones abiertas. Cupo limitado." />
                                        <DisciplineCard delay={0.1} icon="groups" tags={["Lunes","Miercoles","Sabado","Domingo"]} title="Horarios" body="Canchas disponibles de [HORARIO]. Reserva tu espacio con 24h de anticipacion." />
                                                <DisciplineCard delay={0.2} icon="emoji_events" tags={["Torneo","Copa","Amistoso","Clinica"]} title="Eventos" body="Proximo torneo: [FECHA]. Categorias abiertas y master. Premios para los 3 primeros lugares." />
                                                      </div>
                                                          </VideoSection>
                                                            );
                                                            }

                                                            const INSTRUCTORS = [
                                                              { name:"[NOMBRE 1]", disc:"Yoga", from:"#1f5c3d", to:"#0b2a1b", bio:"Especialista en Vinyasa y respiracion consciente.", esp:["Vinyasa","Pranayama"] },
                                                                { name:"[NOMBRE 2]", disc:"Yoga", from:"#2a6f4a", to:"#0e3322", bio:"Enfoque en yoga restaurativo y prenatal.", esp:["Restaurativa","Prenatal"] },
                                                                  { name:"[NOMBRE 3]", disc:"Fitness", from:"#7a3b0f", to:"#2c1606", bio:"Coach de fuerza y acondicionamiento.", esp:["Fuerza","HIIT"] },
                                                                    { name:"[NOMBRE 4]", disc:"Fitness", from:"#8a4412", to:"#321808", bio:"Entrenamiento funcional y movilidad.", esp:["Funcional","Movilidad"] },
                                                                      { name:"[NOMBRE 5]", disc:"Basquet", from:"#9c4f14", to:"#3a1d09", bio:"Ex jugador profesional. Clinicas de fundamentos.", esp:["Skills","Defensa"] },
                                                                        { name:"[NOMBRE 6]", disc:"Basquet", from:"#b65c18", to:"#43210a", bio:"Estratega de juego y preparacion fisica.", esp:["Tactica","Conditioning"] },
                                                                        ];

                                                                        function FlipCard({ p, delay }) {
                                                                          return (
                                                                              <Reveal delay={delay}>
                                                                                    <div className="group cursor-hover" style={{ perspective:"1200px", height:340 }}>
                                                                                            <div style={{ position:"relative", width:"100%", height:"100%", transformStyle:"preserve-3d", transition:"transform 0.6s ease" }} className="group-hover:[transform:rotateY(180deg)]">
                                                                                                      <div className="liquid-glass rounded-[1.5rem] p-7 flex flex-col items-center justify-center text-center" style={{ position:"absolute", inset:0, backfaceVisibility:"hidden", WebkitBackfaceVisibility:"hidden" }}>
                                                                                                                  <GradientPlaceholder from={p.from} to={p.to} style={{ width:120, height:120, borderRadius:"9999px" }} className="mb-5" />
                                                                                                                              <div className="font-heading italic text-3xl leading-none mb-2">{p.name}</div>
                                                                                                                                          <span className="liquid-glass rounded px-3 py-1 text-xs uppercase tracking-[0.12em] text-white/75">{p.disc}</span>
                                                                                                                                                    </div>
                                                                                                                                                              <div className="liquid-glass-strong rounded-[1.5rem] p-7 flex flex-col text-left" style={{ position:"absolute", inset:0, transform:"rotateY(180deg)", backfaceVisibility:"hidden", WebkitBackfaceVisibility:"hidden" }}>
                                                                                                                                                                          <div className="font-heading italic text-2xl mb-2">{p.name}</div>
                                                                                                                                                                                      <p className="text-sm text-white/75 leading-relaxed">{p.bio}</p>
                                                                                                                                                                                                  <div className="flex flex-wrap gap-2 mt-4">{p.esp.map(t => <span key={t} className="liquid-glass rounded px-3 py-1 text-xs text-white/80">{t}</span>)}</div>
                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                              </Reveal>
                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                function Instructores() {
                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                      <section id="instructores" className="relative bg-black px-6 md:px-16 lg:px-20 py-28">
                                                                                                                                                                                                                                            <Kicker>// Equipo</Kicker>
                                                                                                                                                                                                                                                  <TwoLineHeading a="Los mejores" b="instructores" />
                                                                                                                                                                                                                                                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
                                                                                                                                                                                                                                                                {INSTRUCTORS.map((p,i) => <FlipCard key={i} p={p} delay={(i%3)*0.1} />)}
                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                            const GALLERY = [
                                                                                                                                                                                                                                                                              { label:"yoga studio", from:"#1f5c3d", to:"#0b2a1b", span:"md:col-span-2", h:260 },
                                                                                                                                                                                                                                                                                { label:"weights", from:"#7a3b0f", to:"#2c1606", span:"", h:340 },
                                                                                                                                                                                                                                                                                  { label:"basketball", from:"#9c4f14", to:"#3a1d09", span:"", h:260 },
                                                                                                                                                                                                                                                                                    { label:"meditation", from:"#2a6f4a", to:"#0e3322", span:"md:col-span-2", h:280 },
                                                                                                                                                                                                                                                                                      { label:"fitness class", from:"#8a4412", to:"#321808", span:"", h:280 },
                                                                                                                                                                                                                                                                                        { label:"studio exterior", from:"#b65c18", to:"#43210a", span:"", h:260 },
                                                                                                                                                                                                                                                                                        ];

                                                                                                                                                                                                                                                                                        function GalleryCard({ item, idx }) {
                                                                                                                                                                                                                                                                                          const ref = useParallax(0.05);
                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                <Reveal delay={idx*0.07} className={item.span}>
                                                                                                                                                                                                                                                                                                      <div ref={ref} className="cursor-hover rounded-[1.5rem] overflow-hidden" style={{ height:item.h, transition:"transform 0.4s ease, box-shadow 0.4s ease" }} onMouseEnter={e => { e.currentTarget.style.transform="translateZ(30px) scale(1.02)"; e.currentTarget.style.boxShadow="0 30px 80px rgba(0,0,0,0.7)"; }} onMouseLeave={e => { e.currentTarget.style.transform=""; e.currentTarget.style.boxShadow=""; }}>
                                                                                                                                                                                                                                                                                                              <GradientPlaceholder from={item.from} to={item.to} label={item.label} className="w-full h-full" />
                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                        </Reveal>
                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                          function Galeria() {
                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                <section id="galeria" className="relative bg-black px-6 md:px-16 lg:px-20 py-28 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                      <Kicker>// Galeria</Kicker>
                                                                                                                                                                                                                                                                                                                                            <TwoLineHeading a="El espacio" b="que mereces" />
                                                                                                                                                                                                                                                                                                                                                  <div style={{ perspective:"1200px" }}>
                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-1 md:grid-cols-4 gap-5" style={{ transform:"rotateX(5deg)", transformStyle:"preserve-3d" }}>
                                                                                                                                                                                                                                                                                                                                                                    {GALLERY.map((item,i) => <GalleryCard key={i} item={item} idx={i} />)}
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                      </section>
                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                        Object.assign(window, { Basquet, Instructores, Galeria });